name: iris-classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - mlflow>=2.0.0
    - scikit-learn>=1.0.0
    - pandas>=1.3.0
    - matplotlib>=3.4.0
